server:
  port: ${PORT:8080} # Puerto dinámico inyectado por Railway o 8080 por defecto
  servlet:
    context-path: /api/v1 # Prefijo base global de versión para todas las rutas REST

spring:
  application:
    name: clinica-dermatologica-backend # Nombre identificador del servicio

  datasource:
    # URL de conexión JDBC a Supabase o PostgreSQL en la nube
    url: ${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/clinica_db?sslmode=prefer}}}
    username: ${SPRING_DATASOURCE_USERNAME:${PGUSER:${DATABASE_USER:postgres}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:${DATABASE_PASSWORD:postgres}}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Configuración personalizada de Seguridad y Tokens JWT
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:MiClaveSecretaSuperSeguraParaLaClinicaDermatologica2026EsteticaYSalud}
    expiration-time-ms: 28800000

# Configuración de Pasarela de Pagos MercadoPago
mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN:TEST-0000000000000000-000000-000000-00000000000000000000000000000000-000000000}
  webhook-secret: ${MERCADOPAGO_WEBHOOK_SECRET:test_webhook_secret}
  back-urls:
    success: ${FRONTEND_BASE_URL:http://localhost:5173}/turnos/confirmado
    failure: ${FRONTEND_BASE_URL:http://localhost:5173}/turnos/fallido
    pending: ${FRONTEND_BASE_URL:http://localhost:5173}/turnos/pendiente

# Configuración de Inteligencia Artificial con Google Gemini API
gemini:
  api:
    key: ${GEMINI_API_KEY:AQ.Ab8RN6JtRjMndLmRpDeKhB60q8XernnuMzaJXyWk99XmT7zI4A}
    base-url: https://generativelanguage.googleapis.com/v1beta
    model: ${GEMINI_MODEL:gemini-3.5-flash-lite}

# Configuración de Almacenamiento de Fotos Médicas en Supabase Storage
supabase:
  storage:
    url: ${SUPABASE_STORAGE_URL:https://jcsgixxatmqzpdcflevw.supabase.co/storage/v1}
    anon-key: ${SUPABASE_ANON_KEY:sb_publishable_vCQ09c8ZXEKvQeNipnC5gA_d8VQnASl}
    bucket-name: photos
